"""
Test script to demonstrate API usage
Run this to test all endpoints
"""

import requests
import json
import time

BASE_URL = "http://localhost:8000"


def print_section(title):
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}\n")


def test_health():
    """Test health endpoint"""
    print_section("1. Health Check")
    
    response = requests.get(f"{BASE_URL}/health")
    print(f"Status: {response.status_code}")
    print(f"Response: {json.dumps(response.json(), indent=2)}")
    
    return response.status_code == 200


def test_ingest():
    """Test repository ingestion"""
    print_section("2. Ingest Repository")
    
    # Correct format matching IngestRequest model
    payload = {
        "source": {
            "url": "https://github.com/octocat/Hello-World"
        }
    }
    
    print(f"Request: {json.dumps(payload, indent=2)}")
    
    response = requests.post(
        f"{BASE_URL}/api/ingest",
        json=payload
    )
    
    print(f"\nStatus: {response.status_code}")
    print(f"Response: {json.dumps(response.json(), indent=2)}")
    
    return response.status_code == 200


def test_search(repo_id):
    """Test semantic search"""
    print_section("3. Search Repository")
    
    payload = {
        "repo_id": repo_id,
        "query": "main function"
    }
    
    print(f"Request: {json.dumps(payload, indent=2)}")
    
    response = requests.post(
        f"{BASE_URL}/api/search",
        json=payload
    )
    
    print(f"\nStatus: {response.status_code}")
    
    if response.status_code == 200:
        print(f"Response: {json.dumps(response.json(), indent=2)}")
    else:
        print(f"Error: {response.text}")
    
    return response.status_code == 200


def test_create_plan(repo_id):
    """Test plan creation"""
    print_section("4. Create Analysis Plan")
    
    payload = {
        "repo_id": repo_id,
        "query": "Analyze code structure"
    }
    
    print(f"Request: {json.dumps(payload, indent=2)}")
    
    response = requests.post(
        f"{BASE_URL}/api/orchestrator/plan",
        json=payload
    )
    
    print(f"\nStatus: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        print(f"Response: {json.dumps(data, indent=2)}")
        return data.get("plan_id")
    else:
        print(f"Error: {response.text}")
        return None


def test_get_plan(plan_id):
    """Test getting plan details"""
    print_section("5. Get Plan Details")
    
    response = requests.get(
        f"{BASE_URL}/api/orchestrator/plan/{plan_id}"
    )
    
    print(f"Status: {response.status_code}")
    
    if response.status_code == 200:
        print(f"Response: {json.dumps(response.json(), indent=2)}")
    else:
        print(f"Error: {response.text}")
    
    return response.status_code == 200


def test_metrics():
    """Test metrics endpoint"""
    print_section("6. View Metrics")
    
    response = requests.get(f"{BASE_URL}/metrics")
    
    print(f"Status: {response.status_code}")
    print(f"Response: {json.dumps(response.json(), indent=2)}")
    
    return response.status_code == 200


def main():
    """Run all tests"""
    print("\n" + "="*60)
    print("  REPO ANALYZER API - TEST SCRIPT")
    print("="*60)
    
    repo_id = None
    
    try:
        # Test 1: Health check
        if not test_health():
            print("\n❌ Health check failed! Is the server running?")
            return
        
        # Test 2: Ingest repository
        print("\n⏳ Ingesting repository (this may take a minute)...")
        ingest_result = test_ingest()
        
        if ingest_result:
            print("\n✅ Repository ingested successfully!")
            # Extract repo_id from the response
            # For now, we'll use a default since we need to parse the response
            repo_id = "test_repo"  # This will be auto-generated by the service
            time.sleep(2)  # Wait for processing
        else:
            print("\n⚠️  Ingest failed, skipping dependent tests...")
            test_metrics()
            return
        
        # Test 3: Search (requires repo_id)
        if repo_id:
            test_search(repo_id)
        
        # Test 4: Create plan (requires repo_id)
        plan_id = None
        if repo_id:
            plan_id = test_create_plan(repo_id)
        
        # Test 5: Get plan (if created)
        if plan_id:
            time.sleep(1)
            test_get_plan(plan_id)
        
        # Test 6: Metrics
        test_metrics()
        
        print("\n" + "="*60)
        print("  ✅ TEST SCRIPT COMPLETED")
        print("="*60 + "\n")
        
    except requests.exceptions.ConnectionError:
        print("\n❌ ERROR: Cannot connect to server!")
        print("Make sure the server is running:")
        print("  uvicorn main:app --reload")
        print()
    except Exception as e:
        print(f"\n❌ ERROR: {str(e)}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
