from pydantic import BaseModel, Field
from typing import List, Optional

class FileToRead(BaseModel):
    """File identified for reading during analysis"""
    path: str = Field(..., description="Absolute path or relative path from repo root")
    reason: str = Field(..., description="Why this file is relevant to the analysis")

class AnalysisPlan(BaseModel):
    """
    Structured plan generated by Gemini before reading deep code.
    This represents the 'Thinking' phase output.
    """
    approach: str = Field(..., description="High-level strategy for analyzing the repository")
    files_to_read: List[FileToRead] = Field(..., description="List of specific files to inspect")
    rationale: str = Field(..., description="Explanation of why these files were chosen")

class CodeChange(BaseModel):
    """Proposed code modification"""
    file_path: str = Field(..., description="Path to the file to change")
    description: str = Field(..., description="Description of the change")
    original_snippet: Optional[str] = Field(None, description="Code snippet to replace")
    new_snippet: Optional[str] = Field(None, description="New code snippet")
    confidence: str = Field(..., description="Confidence level (High, Medium, Low)")

class AnalysisResult(BaseModel):
    """
    Final output from Gemini analysis.
    """
    summary: str = Field(..., description="Executive summary of the analysis findings")
    findings: List[str] = Field(..., description="Bulleted list of specific technical findings")
    code_changes: List[CodeChange] = Field(default_factory=list, description="Recommended code changes if any")
    security_risks: List[str] = Field(default_factory=list, description="Potential security risks identified")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Overall confidence score (0.0 - 1.0)")
